language: python

matrix:
    include:
        - python: 2.7
          env: TOXENV=django111
        - python: 3.5
          env: TOXENV=django20
        - python: 3.6
          env: TOXENV=django22
        - python: 3.6
          env: TOXENV=django30

install:
  - pip install tox

script: tox
